INSERT INTO public.movie_person_types (id, name) VALUES (1, 'actor');
INSERT INTO public.movie_person_types (id, name) VALUES (2, 'composer');
INSERT INTO public.movie_person_types (id, name) VALUES (3, 'designer');
INSERT INTO public.movie_person_types (id, name) VALUES (4, 'director');
INSERT INTO public.movie_person_types (id, name) VALUES (5, 'editor');
INSERT INTO public.movie_person_types (id, name) VALUES (6, 'operator');
INSERT INTO public.movie_person_types (id, name) VALUES (7, 'producer');
INSERT INTO public.movie_person_types (id, name) VALUES (8, 'screenwriter');
INSERT INTO public.movie_person_types (id, name) VALUES (9, 'voice actor');
INSERT INTO public.movie_person_types (id, name) VALUES (10, 'sound director');
INSERT INTO public.movie_person_types (id, name) VALUES (11, 'music editor');
INSERT INTO public.movie_person_types (id, name) VALUES (12, 'understudy');
INSERT INTO public.movie_person_types (id, name) VALUES (13, 'casting director');
