INSERT INTO public.countries (id, name, currency_id, code) VALUES (1, 'Afghanistan', 2, 'AF');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (2, 'Aland Islands', 2, 'AX');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (3, 'Albania', 2, 'AL');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (4, 'Algeria', 2, 'DZ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (5, 'American Samoa', 2, 'AS');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (6, 'Andorra', 1, 'AD');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (7, 'Angola', 2, 'AO');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (8, 'Anguilla', 2, 'AI');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (9, 'Antarctica', 2, 'AQ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (10, 'Antigua and Barbuda', 2, 'AG');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (11, 'Argentina', 2, 'AR');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (12, 'Armenia', 2, 'AM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (13, 'Aruba', 2, 'AW');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (14, 'Australia', 2, 'AU');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (15, 'Austria', 1, 'AT');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (16, 'Azerbaijan', 2, 'AZ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (17, 'Bahamas', 2, 'BS');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (18, 'Bahrain', 2, 'BH');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (19, 'Bangladesh', 2, 'BD');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (20, 'Barbados', 2, 'BB');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (21, 'Belarus', 2, 'BY');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (22, 'Belgium', 1, 'BE');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (23, 'Belize', 2, 'BZ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (24, 'Benin', 2, 'BJ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (25, 'Bermuda', 2, 'BM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (26, 'Bhutan', 2, 'BT');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (27, 'Bolivia', 2, 'BO');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (28, 'Bonaire, Sint Eustatius and Saba', 2, 'BQ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (29, 'Bosnia and Herzegovina', 2, 'BA');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (30, 'Botswana', 2, 'BW');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (31, 'Bouvet Island', 2, 'BV');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (32, 'Brazil', 2, 'BR');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (33, 'British Indian Ocean Territory', 2, 'IO');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (34, 'Brunei Darussalam', 2, 'BN');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (35, 'Bulgaria', 1, 'BG');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (36, 'Burkina Faso', 2, 'BF');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (37, 'Burundi', 2, 'BI');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (38, 'Cambodia', 2, 'KH');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (39, 'Cameroon', 2, 'CM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (40, 'Canada', 2, 'CA');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (41, 'Cape Verde', 2, 'CV');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (42, 'Cayman Islands', 2, 'KY');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (43, 'Central African Republic', 2, 'CF');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (44, 'Chad', 2, 'TD');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (45, 'Chile', 2, 'CL');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (46, 'China', 2, 'CN');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (47, 'Christmas Island', 2, 'CX');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (48, 'Cocos (Keeling) Islands', 2, 'CC');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (49, 'Colombia', 2, 'CO');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (50, 'Comoros', 2, 'KM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (51, 'Congo', 2, 'CG');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (52, 'Congo, Democratic Republic of the Congo', 2, 'CD');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (53, 'Cook Islands', 2, 'CK');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (54, 'Costa Rica', 2, 'CR');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (55, 'Cote D''Ivoire', 2, 'CI');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (56, 'Croatia', 1, 'HR');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (57, 'Cuba', 2, 'CU');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (58, 'Curacao', 2, 'CW');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (59, 'Cyprus', 1, 'CY');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (60, 'Czech Republic', 1, 'CZ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (61, 'Denmark', 1, 'DK');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (62, 'Djibouti', 2, 'DJ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (63, 'Dominica', 2, 'DM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (64, 'Dominican Republic', 2, 'DO');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (65, 'Ecuador', 2, 'EC');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (66, 'Egypt', 2, 'EG');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (67, 'El Salvador', 2, 'SV');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (68, 'Equatorial Guinea', 2, 'GQ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (69, 'Eritrea', 2, 'ER');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (70, 'Estonia', 1, 'EE');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (71, 'Ethiopia', 2, 'ET');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (72, 'Falkland Islands (Malvinas)', 2, 'FK');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (73, 'Faroe Islands', 2, 'FO');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (74, 'Fiji', 2, 'FJ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (75, 'Finland', 1, 'FI');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (76, 'France', 1, 'FR');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (77, 'French Guiana', 2, 'GF');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (78, 'French Polynesia', 2, 'PF');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (79, 'French Southern Territories', 2, 'TF');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (80, 'Gabon', 2, 'GA');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (81, 'Gambia', 2, 'GM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (82, 'Georgia', 2, 'GE');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (83, 'Germany', 1, 'DE');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (84, 'Ghana', 2, 'GH');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (85, 'Gibraltar', 2, 'GI');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (86, 'Greece', 1, 'GR');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (87, 'Greenland', 2, 'GL');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (88, 'Grenada', 2, 'GD');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (89, 'Guadeloupe', 2, 'GP');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (90, 'Guam', 2, 'GU');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (91, 'Guatemala', 2, 'GT');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (92, 'Guernsey', 2, 'GG');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (93, 'Guinea', 2, 'GN');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (94, 'Guinea-Bissau', 2, 'GW');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (95, 'Guyana', 2, 'GY');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (96, 'Haiti', 2, 'HT');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (97, 'Heard Island and McDonald Islands', 2, 'HM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (98, 'Holy See (Vatican City State)', 1, 'VA');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (99, 'Honduras', 2, 'HN');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (100, 'Hong Kong', 2, 'HK');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (101, 'Hungary', 1, 'HU');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (102, 'Iceland', 2, 'IS');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (103, 'India', 2, 'IN');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (104, 'Indonesia', 2, 'ID');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (105, 'Iran, Islamic Republic of', 2, 'IR');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (106, 'Iraq', 2, 'IQ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (107, 'Ireland', 1, 'IE');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (108, 'Isle of Man', 2, 'IM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (109, 'Israel', 2, 'IL');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (110, 'Italy', 1, 'IT');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (111, 'Jamaica', 2, 'JM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (112, 'Japan', 2, 'JP');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (113, 'Jersey', 2, 'JE');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (114, 'Jordan', 2, 'JO');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (115, 'Kazakhstan', 2, 'KZ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (116, 'Kenya', 2, 'KE');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (117, 'Kiribati', 2, 'KI');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (118, 'Korea, Democratic People''s Republic of', 2, 'KP');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (119, 'Korea, Republic of', 2, 'KR');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (120, 'Kosovo', 1, 'XK');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (121, 'Kuwait', 2, 'KW');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (122, 'Kyrgyzstan', 2, 'KG');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (123, 'Lao People''s Democratic Republic', 2, 'LA');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (124, 'Latvia', 1, 'LV');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (125, 'Lebanon', 2, 'LB');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (126, 'Lesotho', 2, 'LS');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (127, 'Liberia', 2, 'LR');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (128, 'Libyan Arab Jamahiriya', 2, 'LY');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (129, 'Liechtenstein', 2, 'LI');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (130, 'Lithuania', 1, 'LT');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (131, 'Luxembourg', 1, 'LU');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (132, 'Macao', 2, 'MO');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (133, 'Macedonia, the Former Yugoslav Republic of', 2, 'MK');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (134, 'Madagascar', 2, 'MG');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (135, 'Malawi', 2, 'MW');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (136, 'Malaysia', 2, 'MY');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (137, 'Maldives', 2, 'MV');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (138, 'Mali', 2, 'ML');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (139, 'Malta', 1, 'MT');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (140, 'Marshall Islands', 2, 'MH');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (141, 'Martinique', 2, 'MQ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (142, 'Mauritania', 2, 'MR');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (143, 'Mauritius', 2, 'MU');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (144, 'Mayotte', 2, 'YT');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (145, 'Mexico', 2, 'MX');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (146, 'Micronesia, Federated States of', 2, 'FM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (147, 'Moldova, Republic of', 2, 'MD');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (148, 'Monaco', 1, 'MC');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (149, 'Mongolia', 2, 'MN');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (150, 'Montenegro', 1, 'ME');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (151, 'Montserrat', 2, 'MS');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (152, 'Morocco', 2, 'MA');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (153, 'Mozambique', 2, 'MZ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (154, 'Myanmar', 2, 'MM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (155, 'Namibia', 2, 'NA');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (156, 'Nauru', 2, 'NR');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (157, 'Nepal', 2, 'NP');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (158, 'Netherlands', 1, 'NL');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (159, 'Netherlands Antilles', 2, 'AN');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (160, 'New Caledonia', 2, 'NC');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (161, 'New Zealand', 2, 'NZ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (162, 'Nicaragua', 2, 'NI');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (163, 'Niger', 2, 'NE');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (164, 'Nigeria', 2, 'NG');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (165, 'Niue', 2, 'NU');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (166, 'Norfolk Island', 2, 'NF');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (167, 'Northern Mariana Islands', 2, 'MP');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (168, 'Norway', 2, 'NO');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (169, 'Oman', 2, 'OM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (170, 'Pakistan', 2, 'PK');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (171, 'Palau', 2, 'PW');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (172, 'Palestinian Territory, Occupied', 2, 'PS');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (173, 'Panama', 2, 'PA');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (174, 'Papua New Guinea', 2, 'PG');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (175, 'Paraguay', 2, 'PY');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (176, 'Peru', 2, 'PE');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (177, 'Philippines', 2, 'PH');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (178, 'Pitcairn', 2, 'PN');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (179, 'Poland', 2, 'PL');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (180, 'Portugal', 1, 'PT');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (181, 'Puerto Rico', 2, 'PR');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (182, 'Qatar', 2, 'QA');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (183, 'Reunion', 2, 'RE');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (184, 'Romania', 1, 'RO');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (185, 'Russian Federation', 2, 'RU');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (186, 'Rwanda', 2, 'RW');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (187, 'Saint Barthelemy', 1, 'BL');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (188, 'Saint Helena', 2, 'SH');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (189, 'Saint Kitts and Nevis', 2, 'KN');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (190, 'Saint Lucia', 2, 'LC');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (191, 'Saint Martin', 2, 'MF');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (192, 'Saint Pierre and Miquelon', 1, 'PM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (193, 'Saint Vincent and the Grenadines', 2, 'VC');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (194, 'Samoa', 2, 'WS');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (195, 'San Marino', 1, 'SM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (196, 'Sao Tome and Principe', 2, 'ST');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (197, 'Saudi Arabia', 2, 'SA');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (198, 'Senegal', 2, 'SN');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (199, 'Serbia', 2, 'RS');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (200, 'Serbia and Montenegro', 2, 'CS');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (201, 'Seychelles', 2, 'SC');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (202, 'Sierra Leone', 2, 'SL');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (203, 'Singapore', 2, 'SG');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (204, 'St Martin', 2, 'SX');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (205, 'Slovakia', 1, 'SK');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (206, 'Slovenia', 1, 'SI');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (207, 'Solomon Islands', 2, 'SB');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (208, 'Somalia', 2, 'SO');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (209, 'South Africa', 2, 'ZA');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (210, 'South Georgia and the South Sandwich Islands', 2, 'GS');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (211, 'South Sudan', 2, 'SS');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (212, 'Spain', 1, 'ES');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (213, 'Sri Lanka', 2, 'LK');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (214, 'Sudan', 2, 'SD');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (215, 'Suriname', 2, 'SR');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (216, 'Svalbard and Jan Mayen', 2, 'SJ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (217, 'Swaziland', 2, 'SZ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (218, 'Sweden', 1, 'SE');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (219, 'Switzerland', 1, 'CH');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (220, 'Syrian Arab Republic', 2, 'SY');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (221, 'Taiwan, Province of China', 2, 'TW');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (222, 'Tajikistan', 2, 'TJ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (223, 'Tanzania, United Republic of', 2, 'TZ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (224, 'Thailand', 2, 'TH');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (225, 'Timor-Leste', 2, 'TL');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (226, 'Togo', 2, 'TG');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (227, 'Tokelau', 2, 'TK');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (228, 'Tonga', 2, 'TO');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (229, 'Trinidad and Tobago', 2, 'TT');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (230, 'Tunisia', 2, 'TN');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (231, 'Turkey', 2, 'TR');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (232, 'Turkmenistan', 2, 'TM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (233, 'Turks and Caicos Islands', 2, 'TC');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (234, 'Tuvalu', 2, 'TV');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (235, 'Uganda', 2, 'UG');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (236, 'Ukraine', 1, 'UA');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (237, 'United Arab Emirates', 2, 'AE');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (238, 'United Kingdom', 2, 'GB');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (239, 'United States', 2, 'US');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (240, 'United States Minor Outlying Islands', 2, 'UM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (241, 'Uruguay', 2, 'UY');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (242, 'Uzbekistan', 2, 'UZ');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (243, 'Vanuatu', 2, 'VU');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (244, 'Venezuela', 2, 'VE');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (245, 'Viet Nam', 2, 'VN');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (246, 'Virgin Islands, British', 2, 'VG');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (247, 'Virgin Islands, U.s.', 2, 'VI');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (248, 'Wallis and Futuna', 2, 'WF');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (249, 'Western Sahara', 2, 'EH');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (250, 'Yemen', 2, 'YE');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (251, 'Zambia', 2, 'ZM');
INSERT INTO public.countries (id, name, currency_id, code) VALUES (252, 'Zimbabwe', 2, 'ZW');
